@startuml
!include <C4/C4_Container>

LAYOUT_LEFT_RIGHT()

Person(professional, "Healthcare Professional")
System(lpg, "Landing page", "Or other healthcare systems")
System(lrs, "Localisation Register Service", "")
System(psr, "Pseudonym Register Service", "Pseudoniem Register Service")

System(nri, "National Referral Index", "Nationale Verwijsindex")
System(add, "Addressing Service", "")

System(lmr, "Localization Metadata Register", "Localisatie Metadataregister")

Rel(professional, lpg, "")
Rel(lpg, lrs, "Interface: request timeline")
Rel(lrs, psr, "Interface: BSN to base Pseudonym")
Rel(lrs, nri, "Interface: Lookup Referrals")
Rel(nri, psr, "Interface: Exchange PID")
Rel(lrs, add, "Interface: mCSD Find Matching Care Services [ITI-90]")
Rel(lrs, lmr, "Interface: FHIR find imaging studies for PID")
Rel(lmr, psr, "Interface: Exchange PID")


@enduml
